function drawChartByCategory(keepSingles = false) {
  var data = new google.visualization.DataTable();
  data.addColumn("string", "From");
  data.addColumn("string", "To");
  data.addColumn("number", "Weight");
  data.addRows(
    [
      ["sku", "Location Reports", 1],
      ["sku description", "Location Reports", 1],
      ["mst", "Location Reports", 1],
      ["mst description", "Location Reports", 1],
      ["zone", "Location Reports", 1],
      ["location class", "Location Reports", 1],
      ["location name", "Location Reports", 1],
      ["qty on hand", "Location Reports", 1],
      ["qty alloc", "Location Reports", 1],
      ["qty to store", "Location Reports", 1],
      ["qty mvin", "Location Reports", 1],
      ["max cap", "Location Reports", 1],
      ["qty mvot", "Location Reports", 1],
      ["case qty", "Location Reports", 1],
      ["pallet qty", "Location Reports", 1],
      ["qty on hold", "Location Reports", 1],
      ["hold to empty", "Location Reports", 1],
      ["depth", "Location Reports", 1],
      ["pallets", "Location Reports", 1],
      ["pallets to fill loc", "Location Reports", 1],
      ["lic control", "Location Reports", 1],
      ["storage dev description", "Location Reports", 1],
      ["item", "Location Reports", 1],
      ["dept", "Location Reports", 1],
      ["pal qty", "Location Reports", 1],
      ["master strategy", "Location Reports", 1],
      ["location qty alloc", "Location Reports", 1],
      ["tot qty on hand", "Location Reports", 1],
      ["tot qty alloc", "Location Reports", 1],
      ["qty to rec", "Location Reports", 1],
      ["qty on ord", "Location Reports", 1],
      ["hold empty flg", "Location Reports", 1],
      ["master strategy descrip", "Location Reports", 1],
      ["dpt", "Location Reports", 1],
      ["location class description", "Location Reports", 1],
      ["strg dev", "Location Reports", 1],
      ["strg dev description", "Location Reports", 1],
      ["ded type", "Location Reports", 1],
      ["pick seq", "Location Reports", 1],
      ["empty flg", "Location Reports", 1],
      ["hold to emty flg", "Location Reports", 1],
      ["case_qty", "Location Reports", 1],
      ["pal_qty", "Location Reports", 1],
      ["pal_len", "Location Reports", 1],
      ["pal_wid", "Location Reports", 1],
      ["pal_hgt", "Location Reports", 1],
      ["case_len", "Location Reports", 1],
      ["case_wid", "Location Reports", 1],
      ["case_hgt", "Location Reports", 1],
      ["lot control", "Location Reports", 1],
      ["qty movin", "Location Reports", 1],
      ["qty movout", "Location Reports", 1],
      ["hold code", "Location Reports", 1],
      ["hold empid", "Location Reports", 1],
      ["hold datetime", "Location Reports", 1],
      ["strg dev type", "Location Reports", 1],
      ["strg dev depth", "Location Reports", 1],
      ["zone descripton", "Location Reports", 1],
      ["total pallet positions", "Location Reports", 1],
      ["pallet positions occupied", "Location Reports", 1],
      ["pallet positions empty", "Location Reports", 1],
      ["% pallet positions occupied", "Location Reports", 1],
      ["total locations", "Location Reports", 1],
      ["occupied locations", "Location Reports", 1],
      ["empty locations", "Location Reports", 1],
      ["% locations occupied", "Location Reports", 1],
      ["actual pallets in sd", "Location Reports", 1],
      ["max cap pallets in sd", "Location Reports", 1],
      ["location % full", "Location Reports", 1],
      ["# locations pick out", "Location Reports", 1],
      ["license", "Location Reports", 1],
      ["model / lot#", "Location Reports", 1],
      ["carton qty", "Location Reports", 1],
      ["license qty", "Location Reports", 1],
      ["location class descrip", "Location Reports", 1],
      ["location code", "Location Reports", 1],
      ["lic cntrl flag", "Location Reports", 1],
      ["storage dev code", "Location Reports", 1],
      ["storage dev code description", "Location Reports", 1],
      ["location depth", "Location Reports", 1],
      ["location width", "Location Reports", 1],
      ["location height", "Location Reports", 1],
      ["location wt limit", "Location Reports", 1],
      ["empty flag", "Location Reports", 1],
      ["# item locators", "Location Reports", 1],
      ["stg dev location depth", "Location Reports", 1],
      ["location dim pallet capacty", "Location Reports", 1],
      ["strg func", "Location Reports", 1],
      ["storage function description", "Location Reports", 1],
      ["sku", "IC Maintenance Reports", 1],
      ["sku description", "IC Maintenance Reports", 1],
      ["master strategy", "IC Maintenance Reports", 1],
      ["location name", "IC Maintenance Reports", 1],
      ["ded type", "IC Maintenance Reports", 1],
      ["hold to empty", "IC Maintenance Reports", 1],
      ["qty on hand", "IC Maintenance Reports", 1],
      ["qty alloc", "IC Maintenance Reports", 1],
      ["held alloc", "IC Maintenance Reports", 1],
      ["qty mvin", "IC Maintenance Reports", 1],
      ["qty to store", "IC Maintenance Reports", 1],
      ["qty mvot", "IC Maintenance Reports", 1],
      ["offsite on hand", "IC Maintenance Reports", 1],
      ["ttl on_ hand", "IC Maintenance Reports", 1],
      ["qty on hold", "IC Maintenance Reports", 1],
      ["date", "IC Maintenance Reports", 1],
      ["from location", "IC Maintenance Reports", 1],
      ["picker name", "IC Maintenance Reports", 1],
      ["ldap", "IC Maintenance Reports", 1],
      ["dept", "IC Maintenance Reports", 1],
      ["wave", "IC Maintenance Reports", 1],
      ["work assignment", "IC Maintenance Reports", 1],
      ["vehicle class", "IC Maintenance Reports", 1],
      ["cont num", "IC Maintenance Reports", 1],
      ["qty ordered", "IC Maintenance Reports", 1],
      ["qty picked", "IC Maintenance Reports", 1],
      ["location on hand before", "IC Maintenance Reports", 1],
      ["def crtn qty", "IC Maintenance Reports", 1],
      ["sku ttl on hand", "IC Maintenance Reports", 1],
      ["sku ttl on hold", "IC Maintenance Reports", 1],
      ["sku total locs", "IC Maintenance Reports", 1],
      ["sku last rcpt", "IC Maintenance Reports", 1],
      ["store #", "IC Maintenance Reports", 1],
      ["ord type", "IC Maintenance Reports", 1],
      ["outbound order", "IC Maintenance Reports", 1],
      ["allocated date", "IC Maintenance Reports", 1],
      ["dock", "IC Maintenance Reports", 1],
      ["status", "IC Maintenance Reports", 1],
      ["% shipped", "IC Maintenance Reports", 1],
      ["type", "IC Maintenance Reports", 1],
      ["location class", "IC Maintenance Reports", 1],
      ["zone", "IC Maintenance Reports", 1],
      ["location on hand", "IC Maintenance Reports", 1],
      ["qty move in", "IC Maintenance Reports", 1],
      ["ded loc", "IC Maintenance Reports", 1],
      ["ttl on hand", "IC Maintenance Reports", 1],
      ["qty to store and move in", "IC Maintenance Reports", 1],
      ["qty ib", "IC Maintenance Reports", 1],
      ["last recpt date", "IC Maintenance Reports", 1],
      ["date last picked", "IC Maintenance Reports", 1],
      ["# active vendors", "IC Maintenance Reports", 1],
      ["# in season vendors", "IC Maintenance Reports", 1],
      ["# out season vendors", "IC Maintenance Reports", 1],
      ["# inactive vendors", "IC Maintenance Reports", 1],
      ["# clearance vendors", "IC Maintenance Reports", 1],
      ["# delete vendors", "IC Maintenance Reports", 1],
      ["# 0 vendors", "IC Maintenance Reports", 1],
      ["store", "IC Maintenance Reports", 1],
      ["turn", "IC Maintenance Reports", 1],
      ["wrk func", "IC Maintenance Reports", 1],
      ["wka", "IC Maintenance Reports", 1],
      ["# locations for sku", "IC Maintenance Reports", 1],
      ["dt/time wka added", "IC Maintenance Reports", 1],
      ["pick wka", "IC Maintenance Reports", 1],
      ["sku's in location", "IC Maintenance Reports", 1],
      ["sku's on wka", "IC Maintenance Reports", 1],
      ["sku's on po", "IC Maintenance Reports", 1],
      ["cases alloc", "IC Maintenance Reports", 1],
      ["po #", "IC Maintenance Reports", 1],
      ["mx error check", "IC Maintenance Reports", 1],
      ["current picker", "IC Maintenance Reports", 1],
      ["ded on hand", "IC Maintenance Reports", 1],
      ["sku ttl pallets on hand", "IC Maintenance Reports", 1],
      ["ttl # locs", "IC Maintenance Reports", 1],
      ["# ded locs", "IC Maintenance Reports", 1],
      ["cartons pick from dedloc last 45 days", "IC Maintenance Reports", 1],
      ["ttl cartons picked in last 45 days", "IC Maintenance Reports", 1],
      ["ttl cartons picked in last year", "IC Maintenance Reports", 1],
      ["date last receive'd", "IC Maintenance Reports", 1],
      ["pallet qty", "IC Maintenance Reports", 1],
      ["case qty", "IC Maintenance Reports", 1],
      ["max cap", "IC Maintenance Reports", 1],
      ["pallet qty + 1 cartons", "IC Maintenance Reports", 1],
      [
        "shorcut key for entry into item/location modify",
        "IC Maintenance Reports",
        1,
      ],
      ["datetime picked", "IC Maintenance Reports", 1],
      ["model / lot", "IC Maintenance Reports", 1],
      ["ob po", "IC Maintenance Reports", 1],
      ["ob ord type", "IC Maintenance Reports", 1],
      ["picker", "IC Maintenance Reports", 1],
      ["pick cont", "IC Maintenance Reports", 1],
      ["qty sched", "IC Maintenance Reports", 1],
      ["from loc", "IC Maintenance Reports", 1],
      ["vehicle cls", "IC Maintenance Reports", 1],
      ["vehicle type", "IC Maintenance Reports", 1],
      ["cube of sku", "IC Maintenance Reports", 1],
      ["cube of po", "IC Maintenance Reports", 1],
      ["ship dc", "IC Maintenance Reports", 1],
      ["allocated datetime", "IC Maintenance Reports", 1],
      ["receive str/dc", "IC Maintenance Reports", 1],
      ["fb #", "IC Maintenance Reports", 1],
      ["bol #", "IC Maintenance Reports", 1],
      ["carr", "IC Maintenance Reports", 1],
      ["trailer #", "IC Maintenance Reports", 1],
      ["po type", "IC Maintenance Reports", 1],
      ["item description", "IC Maintenance Reports", 1],
      ["license #", "IC Maintenance Reports", 1],
      ["lot", "IC Maintenance Reports", 1],
      ["qty", "IC Maintenance Reports", 1],
      ["function and emp id", "IC Maintenance Reports", 1],
      ["time completed", "IC Maintenance Reports", 1],
      ["license", "IC Maintenance Reports", 1],
      ["master license", "IC Maintenance Reports", 1],
      ["lot #", "IC Maintenance Reports", 1],
      ["lic qty", "IC Maintenance Reports", 1],
      ["license location", "IC Maintenance Reports", 1],
      ["inbound po#", "IC Maintenance Reports", 1],
      ["last receive datetime", "IC Maintenance Reports", 1],
      ["last putw date location", "IC Maintenance Reports", 1],
      ["last repl date location", "IC Maintenance Reports", 1],
      ["itemloc location", "IC Maintenance Reports", 1],
      ["itemloc sku", "IC Maintenance Reports", 1],
      ["itemloc on hand", "IC Maintenance Reports", 1],
      ["stage location", "IC Maintenance Reports", 1],
      ["wrk func code", "IC Maintenance Reports", 1],
      ["datetime added", "IC Maintenance Reports", 1],
      ["replen queue chk", "IC Maintenance Reports", 1],
      ["putaway queue chk", "IC Maintenance Reports", 1],
      ["cleanup staged work assignment", "IC Maintenance Reports", 1],
      ["cleanup putaway license", "IC Maintenance Reports", 1],
      ["work type", "IC Maintenance Reports", 1],
      ["rpt id", "IC Maintenance Reports", 1],
      ["report name", "IC Maintenance Reports", 1],
      ["vendor #", "IC Maintenance Reports", 1],
      ["vendor name", "IC Maintenance Reports", 1],
      ["cn flg", "IC Maintenance Reports", 1],
      ["e mail address", "IC Maintenance Reports", 1],
      ["inbound po", "IC Maintenance Reports", 1],
      ["inbound load #", "IC Maintenance Reports", 1],
      ["inbound order type", "IC Maintenance Reports", 1],
      ["model/lot vendor name", "IC Maintenance Reports", 1],
      ["qty ord", "IC Maintenance Reports", 1],
      ["qty received", "IC Maintenance Reports", 1],
      ["orig po create date", "IC Maintenance Reports", 1],
      ["adj date & time", "IC Accuracy Reports", 1],
      ["day", "IC Accuracy Reports", 1],
      ["sku", "IC Accuracy Reports", 1],
      ["sku description", "IC Accuracy Reports", 1],
      ["dept", "IC Accuracy Reports", 1],
      ["adj loc", "IC Accuracy Reports", 1],
      ["model/ lot", "IC Accuracy Reports", 1],
      ["license", "IC Accuracy Reports", 1],
      ["new qty", "IC Accuracy Reports", 1],
      ["orig qty", "IC Accuracy Reports", 1],
      ["qty adj", "IC Accuracy Reports", 1],
      ["adjust cost", "IC Accuracy Reports", 1],
      ["abs adjust cost", "IC Accuracy Reports", 1],
      ["cartons adj", "IC Accuracy Reports", 1],
      ["abs cartons", "IC Accuracy Reports", 1],
      ["adj code", "IC Accuracy Reports", 1],
      ["adjustment description", "IC Accuracy Reports", 1],
      ["emp id", "IC Accuracy Reports", 1],
      ["wrk fnc", "IC Accuracy Reports", 1],
      ["week ind", "IC Accuracy Reports", 1],
      ["week start", "IC Accuracy Reports", 1],
      ["week end", "IC Accuracy Reports", 1],
      ["expected qty", "IC Accuracy Reports", 1],
      ["actual qty", "IC Accuracy Reports", 1],
      ["inv accuracy %", "IC Accuracy Reports", 1],
      ["locations counted", "IC Accuracy Reports", 1],
      ["locations in error", "IC Accuracy Reports", 1],
      ["location accuracy %", "IC Accuracy Reports", 1],
      ["expected $$", "IC Accuracy Reports", 1],
      ["actual $$", "IC Accuracy Reports", 1],
      ["$$ inv accuracy %", "IC Accuracy Reports", 1],
      ["empty locations counted", "IC Accuracy Reports", 1],
      ["work fnc code", "IC Accuracy Reports", 1],
      ["# auto wka", "IC Accuracy Reports", 1],
      ["ttl # wka", "IC Accuracy Reports", 1],
      ["# locations", "IC Accuracy Reports", 1],
      ["zone", "IC Accuracy Reports", 1],
      ["count datetime", "IC Accuracy Reports", 1],
      ["location name", "IC Accuracy Reports", 1],
      ["orig emp id", "IC Accuracy Reports", 1],
      ["wrk func", "IC Accuracy Reports", 1],
      ["count qty", "IC Accuracy Reports", 1],
      ["variance", "IC Accuracy Reports", 1],
      ["vari $$", "IC Accuracy Reports", 1],
      ["wka", "IC Accuracy Reports", 1],
      ["adj description", "IC Accuracy Reports", 1],
      ["unit cost", "IC Accuracy Reports", 1],
      ["lot cntrl", "IC Accuracy Reports", 1],
      ["lic cntrl", "IC Accuracy Reports", 1],
      ["locations in building", "IC Accuracy Reports", 1],
      ["quantity on hand", "IC Accuracy Reports", 1],
      ["quantity allocated", "IC Accuracy Reports", 1],
      ["open order qty", "IC Accuracy Reports", 1],
      ["# of open orders", "IC Accuracy Reports", 1],
      ["45 day pick hist", "IC Accuracy Reports", 1],
      ["45 day receive hist", "IC Accuracy Reports", 1],
      ["putaway history", "IC Accuracy Reports", 1],
      ["ib qty on order", "IC Accuracy Reports", 1],
      ["cca manual", "IC Accuracy Reports", 1],
      ["cca rf", "IC Accuracy Reports", 1],
      ["total cca", "IC Accuracy Reports", 1],
      ["cca loss/gain", "IC Accuracy Reports", 1],
      ["wka #", "IC Accuracy Reports", 1],
      ["item #", "IC Accuracy Reports", 1],
      ["wfc", "IC Accuracy Reports", 1],
      ["type", "IC Accuracy Reports", 1],
      ["date", "IC Accuracy Reports", 1],
      ["wka barcode", "IC Accuracy Reports", 1],
      ["qty", "IC Accuracy Reports", 1],
      ["to loc", "IC Accuracy Reports", 1],
      ["location strg fnc", "IC Accuracy Reports", 1],
      ["putaway id", "IC Accuracy Reports", 1],
      ["datetime putw", "IC Accuracy Reports", 1],
      ["receive id", "IC Accuracy Reports", 1],
      ["datetime receive", "IC Accuracy Reports", 1],
      ["work type", "IC Accuracy Reports", 1],
      ["datetime", "IC Accuracy Reports", 1],
      ["name", "IC Accuracy Reports", 1],
      ["qty sched", "IC Accuracy Reports", 1],
      ["qty actual", "IC Accuracy Reports", 1],
      ["on hand before", "IC Accuracy Reports", 1],
      ["on hand after", "IC Accuracy Reports", 1],
      ["license or wka #", "IC Accuracy Reports", 1],
      ["sku", "Slotting Reports", 1],
      ["sku description", "Slotting Reports", 1],
      ["mstr strategy description", "Slotting Reports", 1],
      ["total qty", "Slotting Reports", 1],
      ["ttl cartons", "Slotting Reports", 1],
      ["cp cartons", "Slotting Reports", 1],
      ["# cp wka", "Slotting Reports", 1],
      ["cp pallets", "Slotting Reports", 1],
      ["cp cube", "Slotting Reports", 1],
      ["fp cartons", "Slotting Reports", 1],
      ["# fp wka", "Slotting Reports", 1],
      ["fp pallets", "Slotting Reports", 1],
      ["fp cube", "Slotting Reports", 1],
      ["% cp", "Slotting Reports", 1],
      ["build on", "Slotting Reports", 1],
      ["po type", "Slotting Reports", 1],
      ["master strategy", "Slotting Reports", 1],
      ["ded loc", "Slotting Reports", 1],
      ["dept", "Slotting Reports", 1],
      ["cs qty", "Slotting Reports", 1],
      ["pallet qty", "Slotting Reports", 1],
      ["max cap", "Slotting Reports", 1],
      ["max cap pallets", "Slotting Reports", 1],
      ["total on hand", "Slotting Reports", 1],
      ["pallets on hand", "Slotting Reports", 1],
      ["cartons on order", "Slotting Reports", 1],
      ["ded location turns", "Slotting Reports", 1],
      ["sdc", "SKU/Item Reports", 1],
      ["sku", "SKU/Item Reports", 1],
      ["description", "SKU/Item Reports", 1],
      ["dept", "SKU/Item Reports", 1],
      ["itm config seq", "SKU/Item Reports", 1],
      ["case qty", "SKU/Item Reports", 1],
      ["case length", "SKU/Item Reports", 1],
      ["case width", "SKU/Item Reports", 1],
      ["case height", "SKU/Item Reports", 1],
      ["case wgt", "SKU/Item Reports", 1],
      ["case cube", "SKU/Item Reports", 1],
      ["pallet qty", "SKU/Item Reports", 1],
      ["pallet length", "SKU/Item Reports", 1],
      ["pallet width", "SKU/Item Reports", 1],
      ["pallet height", "SKU/Item Reports", 1],
      ["pallet weight", "SKU/Item Reports", 1],
      ["pallet cube", "SKU/Item Reports", 1],
      ["qty on hand", "SKU/Item Reports", 1],
      ["def rec crtn qty", "SKU/Item Reports", 1],
      ["def pik crtn qty", "SKU/Item Reports", 1],
      ["ti", "SKU/Item Reports", 1],
      ["hi", "SKU/Item Reports", 1],
      ["layer qty", "SKU/Item Reports", 1],
      ["master strategy", "SKU/Item Reports", 1],
      ["build on", "SKU/Item Reports", 1],
      ["stack lmt", "SKU/Item Reports", 1],
      ["unit value", "SKU/Item Reports", 1],
      ["last cycle cnt", "SKU/Item Reports", 1],
      ["last stg loc", "SKU/Item Reports", 1],
      ["last dt rcvd", "SKU/Item Reports", 1],
      ["sku description", "SKU/Item Reports", 1],
      ["location name", "SKU/Item Reports", 1],
      ["model lot", "SKU/Item Reports", 1],
      ["hold on rcpt", "SKU/Item Reports", 1],
      ["hold code", "SKU/Item Reports", 1],
      ["location on hand", "SKU/Item Reports", 1],
      ["location qty on hold", "SKU/Item Reports", 1],
      ["emp id", "SKU/Item Reports", 1],
      ["datetime added", "SKU/Item Reports", 1],
      ["mx location chk (# skus)", "SKU/Item Reports", 1],
      ["zone", "Miscellaneous Reports", 1],
      ["vehicle type func", "Miscellaneous Reports", 1],
      ["repl wka", "Miscellaneous Reports", 1],
      ["wka bar code", "Miscellaneous Reports", 1],
      ["ovr hld", "Miscellaneous Reports", 1],
      ["status", "Miscellaneous Reports", 1],
      ["sku", "Miscellaneous Reports", 1],
      ["from loc", "Miscellaneous Reports", 1],
      ["qty", "Miscellaneous Reports", 1],
      ["pallets", "Miscellaneous Reports", 1],
      ["to loc", "Miscellaneous Reports", 1],
      ["location on hand", "Miscellaneous Reports", 1],
      ["location maxcap", "Miscellaneous Reports", 1],
      ["stage location", "Miscellaneous Reports", 1],
      ["stage license", "Miscellaneous Reports", 1],
      ["trailer #", "Miscellaneous Reports", 1],
      ["yard loc", "Miscellaneous Reports", 1],
      ["master strategy description", "Miscellaneous Reports", 1],
      ["datetime added", "Miscellaneous Reports", 1],
      ["license", "Miscellaneous Reports", 1],
      ["wrk fnc", "Miscellaneous Reports", 1],
      ["pri", "Miscellaneous Reports", 1],
      ["prob type", "Miscellaneous Reports", 1],
      ["user prob type", "Miscellaneous Reports", 1],
      ["problem description", "Miscellaneous Reports", 1],
      ["orig emp", "Miscellaneous Reports", 1],
      ["tran #", "Miscellaneous Reports", 1],
      ["status description", "Miscellaneous Reports", 1],
      ["ib load #", "Miscellaneous Reports", 1],
      ["model lot", "Miscellaneous Reports", 1],
      ["master strategy", "Miscellaneous Reports", 1],
      ["sku description", "Miscellaneous Reports", 1],
      ["rcv case qty", "Miscellaneous Reports", 1],
      ["rcv pallet qty", "Miscellaneous Reports", 1],
      ["location name", "Miscellaneous Reports", 1],
      ["pr location", "Miscellaneous Reports", 1],
      ["wka", "Miscellaneous Reports", 1],
      ["fifo datetime", "Miscellaneous Reports", 1],
      ["hold code flg", "Miscellaneous Reports", 1],
      ["rtn flg", "Miscellaneous Reports", 1],
      ["dmg flg", "Miscellaneous Reports", 1],
      ["rcv pt", "Miscellaneous Reports", 1],
      ["hot itm flg", "Miscellaneous Reports", 1],
      ["src doc num", "Miscellaneous Reports", 1],
      ["location type", "Miscellaneous Reports", 1],
      ["location hold", "Miscellaneous Reports", 1],
      ["scac", "Miscellaneous Reports", 1],
      ["trailer status", "Miscellaneous Reports", 1],
      ["arrival", "Miscellaneous Reports", 1],
      ["inb / outb", "Miscellaneous Reports", 1],
      ["empty/ full", "Miscellaneous Reports", 1],
      ["ob freight bill", "Miscellaneous Reports", 1],
      ["hold code", "Miscellaneous Reports", 1],
      ["storage trailer contents", "Miscellaneous Reports", 1],
      ["catalyst location", "Miscellaneous Reports", 1],
      ["yms load #", "Miscellaneous Reports", 1],
      ["val code", "Miscellaneous Reports", 1],
    ]
      //   .map(([a, b, c]) => [b, a, c])
      .sort((l1, l2) => l1[0].localeCompare(l2[0]))
      .filter(
        (element, index, ary) =>
          ary.filter((el) => keepSingles || el[0] === element[0]).length > 1
      )
  );

  // Sets chart options.
  var options = {
    width: 600,
  };

  // Instantiates and draws our chart, passing in some options.
  var chart = new google.visualization.Sankey(
    document.getElementById("sankey_basic")
  );
  chart.draw(data, options);
}
