function drawChartByReport(keepSingles = false) {
  var data = new google.visualization.DataTable();
  data.addColumn("string", "From");
  data.addColumn("string", "To");
  data.addColumn("number", "Weight");
  data.addRows(
    [
      ["sku", "consolidation report", 1],
      ["sku description", "consolidation report", 1],
      ["mst", "consolidation report", 1],
      ["mst description", "consolidation report", 1],
      ["zone", "consolidation report", 1],
      ["location class", "consolidation report", 1],
      ["location name", "consolidation report", 1],
      ["qty on hand", "consolidation report", 1],
      ["qty alloc", "consolidation report", 1],
      ["qty to store", "consolidation report", 1],
      ["qty mvin", "consolidation report", 1],
      ["max cap", "consolidation report", 1],
      ["qty mvot", "consolidation report", 1],
      ["case qty", "consolidation report", 1],
      ["pallet qty", "consolidation report", 1],
      ["qty on hold", "consolidation report", 1],
      ["hold to empty", "consolidation report", 1],
      ["depth", "consolidation report", 1],
      ["pallets", "consolidation report", 1],
      ["pallets to fill loc", "consolidation report", 1],
      ["lic control", "consolidation report", 1],
      ["storage dev description", "consolidation report", 1],
      ["location name", "SKUs with dedicated locs", 1],
      ["item", "SKUs with dedicated locs", 1],
      ["sku description", "SKUs with dedicated locs", 1],
      ["dept", "SKUs with dedicated locs", 1],
      ["case qty", "SKUs with dedicated locs", 1],
      ["pal qty", "SKUs with dedicated locs", 1],
      ["master strategy", "SKUs with dedicated locs", 1],
      ["max cap", "SKUs with dedicated locs", 1],
      ["qty on hand", "SKUs with dedicated locs", 1],
      ["location qty alloc", "SKUs with dedicated locs", 1],
      ["tot qty on hand", "SKUs with dedicated locs", 1],
      ["tot qty alloc", "SKUs with dedicated locs", 1],
      ["qty to rec", "SKUs with dedicated locs", 1],
      ["qty on ord", "SKUs with dedicated locs", 1],
      ["hold empty flg", "SKUs with dedicated locs", 1],
      ["location name", "Location report with SKU", 1],
      ["sku", "Location report with SKU", 1],
      ["sku description", "Location report with SKU", 1],
      ["master strategy", "Location report with SKU", 1],
      ["master strategy descrip", "Location report with SKU", 1],
      ["dpt", "Location report with SKU", 1],
      ["location class", "Location report with SKU", 1],
      ["location class description", "Location report with SKU", 1],
      ["zone", "Location report with SKU", 1],
      ["strg dev", "Location report with SKU", 1],
      ["strg dev description", "Location report with SKU", 1],
      ["ded type", "Location report with SKU", 1],
      ["pick seq", "Location report with SKU", 1],
      ["empty flg", "Location report with SKU", 1],
      ["hold to emty flg", "Location report with SKU", 1],
      ["case_qty", "Location report with SKU", 1],
      ["pal_qty", "Location report with SKU", 1],
      ["pal_len", "Location report with SKU", 1],
      ["pal_wid", "Location report with SKU", 1],
      ["pal_hgt", "Location report with SKU", 1],
      ["case_len", "Location report with SKU", 1],
      ["case_wid", "Location report with SKU", 1],
      ["case_hgt", "Location report with SKU", 1],
      ["qty on hand", "Location report with SKU", 1],
      ["max cap", "Location report with SKU", 1],
      ["lot control", "Location report with SKU", 1],
      ["qty alloc", "Location report with SKU", 1],
      ["qty to store", "Location report with SKU", 1],
      ["qty movin", "Location report with SKU", 1],
      ["qty movout", "Location report with SKU", 1],
      ["qty on hold", "Location report with SKU", 1],
      ["hold code", "Location report with SKU", 1],
      ["hold empid", "Location report with SKU", 1],
      ["hold datetime", "Location report with SKU", 1],
      ["pallets", "Location report with SKU", 1],
      ["strg dev type", "Storage device", 1],
      ["strg dev depth", "Storage device", 1],
      ["ded type", "Storage device", 1],
      ["zone", "Storage device", 1],
      ["zone descripton", "Storage device", 1],
      ["total pallet positions", "Storage device", 1],
      ["pallet positions occupied", "Storage device", 1],
      ["pallet positions empty", "Storage device", 1],
      ["% pallet positions occupied", "Storage device", 1],
      ["total locations", "Storage device", 1],
      ["occupied locations", "Storage device", 1],
      ["empty locations", "Storage device", 1],
      ["% locations occupied", "Storage device", 1],
      ["actual pallets in sd", "Storage device", 1],
      ["max cap pallets in sd", "Storage device", 1],
      ["location % full", "Storage device", 1],
      ["# locations pick out", "Storage device", 1],
      ["strg dev type", "Locations by license and lot control", 1],
      ["strg dev depth", "Locations by license and lot control", 1],
      ["ded type", "Locations by license and lot control", 1],
      ["zone", "Locations by license and lot control", 1],
      ["zone descripton", "Locations by license and lot control", 1],
      ["total pallet positions", "Locations by license and lot control", 1],
      ["pallet positions occupied", "Locations by license and lot control", 1],
      ["pallet positions empty", "Locations by license and lot control", 1],
      [
        "% pallet positions occupied",
        "Locations by license and lot control",
        1,
      ],
      ["total locations", "Locations by license and lot control", 1],
      ["occupied locations", "Locations by license and lot control", 1],
      ["empty locations", "Locations by license and lot control", 1],
      ["% locations occupied", "Locations by license and lot control", 1],
      ["actual pallets in sd", "Locations by license and lot control", 1],
      ["max cap pallets in sd", "Locations by license and lot control", 1],
      ["location % full", "Locations by license and lot control", 1],
      ["# locations pick out", "Locations by license and lot control", 1],
      ["sku", "Locations and license", 1],
      ["location name", "Locations and license", 1],
      ["location class", "Locations and license", 1],
      ["zone", "Locations and license", 1],
      ["license", "Locations and license", 1],
      ["model / lot#", "Locations and license", 1],
      ["carton qty", "Locations and license", 1],
      ["pallet qty", "Locations and license", 1],
      ["license qty", "Locations and license", 1],
      ["location name", "Location report", 1],
      ["location class", "Location report", 1],
      ["location class descrip", "Location report", 1],
      ["location code", "Location report", 1],
      ["zone", "Location report", 1],
      ["ded type", "Location report", 1],
      ["lic cntrl flag", "Location report", 1],
      ["storage dev code", "Location report", 1],
      ["storage dev code description", "Location report", 1],
      ["location depth", "Location report", 1],
      ["location width", "Location report", 1],
      ["location height", "Location report", 1],
      ["location wt limit", "Location report", 1],
      ["empty flag", "Location report", 1],
      ["# item locators", "Location report", 1],
      ["pick seq", "Location report", 1],
      ["strg dev type", "Location report", 1],
      ["stg dev location depth", "Location report", 1],
      ["location dim pallet capacty", "Location report", 1],
      ["strg func", "Location report", 1],
      ["storage function description", "Location report", 1],
      ["sku", "Allocated no replen", 1],
      ["sku description", "Allocated no replen", 1],
      ["master strategy", "Allocated no replen", 1],
      ["location name", "Allocated no replen", 1],
      ["ded type", "Allocated no replen", 1],
      ["hold to empty", "Allocated no replen", 1],
      ["qty on hand", "Allocated no replen", 1],
      ["qty alloc", "Allocated no replen", 1],
      ["held alloc", "Allocated no replen", 1],
      ["qty mvin", "Allocated no replen", 1],
      ["qty to store", "Allocated no replen", 1],
      ["qty mvot", "Allocated no replen", 1],
      ["offsite on hand", "Allocated no replen", 1],
      ["ttl on_ hand", "Allocated no replen", 1],
      ["qty on hold", "Allocated no replen", 1],
      ["date", "Short/Zero pick report", 1],
      ["from location", "Short/Zero pick report", 1],
      ["sku", "Short/Zero pick report", 1],
      ["picker name", "Short/Zero pick report", 1],
      ["ldap", "Short/Zero pick report", 1],
      ["dept", "Short/Zero pick report", 1],
      ["wave", "Short/Zero pick report", 1],
      ["work assignment", "Short/Zero pick report", 1],
      ["vehicle class", "Short/Zero pick report", 1],
      ["cont num", "Short/Zero pick report", 1],
      ["qty ordered", "Short/Zero pick report", 1],
      ["qty picked", "Short/Zero pick report", 1],
      ["location on hand before", "Short/Zero pick report", 1],
      ["def crtn qty", "Short/Zero pick report", 1],
      ["sku ttl on hand", "Short/Zero pick report", 1],
      ["sku ttl on hold", "Short/Zero pick report", 1],
      ["sku total locs", "Short/Zero pick report", 1],
      ["sku last rcpt", "Short/Zero pick report", 1],
      ["store #", "Short/Zero pick report", 1],
      ["ord type", "Short/Zero pick report", 1],
      ["outbound order", "Short/Zero pick report", 1],
      ["allocated date", "Short/Zero pick report", 1],
      ["dock", "Short/Zero pick report", 1],
      ["status", "Short/Zero pick report", 1],
      ["% shipped", "Short/Zero pick report", 1],
      ["type", "Short/Zero pick report", 1],
      ["sku", "Over allocated storage", 1],
      ["sku description", "Over allocated storage", 1],
      ["master strategy", "Over allocated storage", 1],
      ["location name", "Over allocated storage", 1],
      ["location class", "Over allocated storage", 1],
      ["zone", "Over allocated storage", 1],
      ["qty alloc", "Over allocated storage", 1],
      ["location on hand", "Over allocated storage", 1],
      ["qty move in", "Over allocated storage", 1],
      ["sku", "Dedicated SKUs with zero on-hand", 1],
      ["dept", "Dedicated SKUs with zero on-hand", 1],
      ["sku description", "Dedicated SKUs with zero on-hand", 1],
      ["master strategy", "Dedicated SKUs with zero on-hand", 1],
      ["ded loc", "Dedicated SKUs with zero on-hand", 1],
      ["location class", "Dedicated SKUs with zero on-hand", 1],
      ["ttl on hand", "Dedicated SKUs with zero on-hand", 1],
      ["qty to store and move in", "Dedicated SKUs with zero on-hand", 1],
      ["qty ib", "Dedicated SKUs with zero on-hand", 1],
      ["last recpt date", "Dedicated SKUs with zero on-hand", 1],
      ["date last picked", "Dedicated SKUs with zero on-hand", 1],
      ["# active vendors", "Dedicated SKUs with zero on-hand", 1],
      ["# in season vendors", "Dedicated SKUs with zero on-hand", 1],
      ["# out season vendors", "Dedicated SKUs with zero on-hand", 1],
      ["# inactive vendors", "Dedicated SKUs with zero on-hand", 1],
      ["# clearance vendors", "Dedicated SKUs with zero on-hand", 1],
      ["# delete vendors", "Dedicated SKUs with zero on-hand", 1],
      ["# 0 vendors", "Dedicated SKUs with zero on-hand", 1],
      ["allocated date", "Full-Pallet allocated from dedicated location", 1],
      ["store", "Full-Pallet allocated from dedicated location", 1],
      ["turn", "Full-Pallet allocated from dedicated location", 1],
      ["dock", "Full-Pallet allocated from dedicated location", 1],
      ["wrk func", "Full-Pallet allocated from dedicated location", 1],
      ["vehicle class", "Full-Pallet allocated from dedicated location", 1],
      ["zone", "Full-Pallet allocated from dedicated location", 1],
      ["wka", "Full-Pallet allocated from dedicated location", 1],
      ["sku", "Full-Pallet allocated from dedicated location", 1],
      [
        "# locations for sku",
        "Full-Pallet allocated from dedicated location",
        1,
      ],
      ["master strategy", "Full-Pallet allocated from dedicated location", 1],
      ["location name", "Full-Pallet allocated from dedicated location", 1],
      ["dt/time wka added", "Full-Pallet allocated from dedicated location", 1],
      ["allocated date", "MX WKA Check", 1],
      ["turn", "MX WKA Check", 1],
      ["dock", "MX WKA Check", 1],
      ["store", "MX WKA Check", 1],
      ["pick wka", "MX WKA Check", 1],
      ["vehicle class", "MX WKA Check", 1],
      ["wrk func", "MX WKA Check", 1],
      ["location name", "MX WKA Check", 1],
      ["sku", "MX WKA Check", 1],
      ["sku's in location", "MX WKA Check", 1],
      ["sku's on wka", "MX WKA Check", 1],
      ["sku's on po", "MX WKA Check", 1],
      ["cases alloc", "MX WKA Check", 1],
      ["po #", "MX WKA Check", 1],
      ["mx error check", "MX WKA Check", 1],
      ["current picker", "MX WKA Check", 1],
      ["sku", "Dedicated pick history", 1],
      ["sku description", "Dedicated pick history", 1],
      ["dept", "Dedicated pick history", 1],
      ["ded type", "Dedicated pick history", 1],
      ["ded loc", "Dedicated pick history", 1],
      ["ded on hand", "Dedicated pick history", 1],
      ["zone", "Dedicated pick history", 1],
      ["sku ttl on hand", "Dedicated pick history", 1],
      ["sku ttl pallets on hand", "Dedicated pick history", 1],
      ["ttl # locs", "Dedicated pick history", 1],
      ["# ded locs", "Dedicated pick history", 1],
      ["cartons pick from dedloc last 45 days", "Dedicated pick history", 1],
      ["ttl cartons picked in last 45 days", "Dedicated pick history", 1],
      ["ttl cartons picked in last year", "Dedicated pick history", 1],
      ["date last receive'd", "Dedicated pick history", 1],
      ["# active vendors", "Dedicated pick history", 1],
      ["# in season vendors", "Dedicated pick history", 1],
      ["# out season vendors", "Dedicated pick history", 1],
      ["# inactive vendors", "Dedicated pick history", 1],
      ["# clearance vendors", "Dedicated pick history", 1],
      ["# delete vendors", "Dedicated pick history", 1],
      ["# 0 vendors", "Dedicated pick history", 1],
      ["location name", "Max Capacity Report", 1],
      ["zone", "Max Capacity Report", 1],
      ["location class", "Max Capacity Report", 1],
      ["sku", "Max Capacity Report", 1],
      ["sku description", "Max Capacity Report", 1],
      ["qty on hand", "Max Capacity Report", 1],
      ["qty alloc", "Max Capacity Report", 1],
      ["pallet qty", "Max Capacity Report", 1],
      ["case qty", "Max Capacity Report", 1],
      ["max cap", "Max Capacity Report", 1],
      ["pallet qty + 1 cartons", "Max Capacity Report", 1],
      [
        "shorcut key for entry into item/location modify",
        "Max Capacity Report",
        1,
      ],
      ["datetime picked", "Outbound Shipment Check", 1],
      ["sku", "Outbound Shipment Check", 1],
      ["model / lot", "Outbound Shipment Check", 1],
      ["ob po", "Outbound Shipment Check", 1],
      ["ob ord type", "Outbound Shipment Check", 1],
      ["picker", "Outbound Shipment Check", 1],
      ["wrk func", "Outbound Shipment Check", 1],
      ["pick cont", "Outbound Shipment Check", 1],
      ["qty sched", "Outbound Shipment Check", 1],
      ["qty picked", "Outbound Shipment Check", 1],
      ["from loc", "Outbound Shipment Check", 1],
      ["vehicle cls", "Outbound Shipment Check", 1],
      ["vehicle type", "Outbound Shipment Check", 1],
      ["cube of sku", "Outbound Shipment Check", 1],
      ["cube of po", "Outbound Shipment Check", 1],
      ["ship dc", "Outbound Shipment Check", 1],
      ["allocated datetime", "Outbound Shipment Check", 1],
      ["receive str/dc", "Outbound Shipment Check", 1],
      ["turn", "Outbound Shipment Check", 1],
      ["dock", "Outbound Shipment Check", 1],
      ["fb #", "Outbound Shipment Check", 1],
      ["bol #", "Outbound Shipment Check", 1],
      ["carr", "Outbound Shipment Check", 1],
      ["trailer #", "Outbound Shipment Check", 1],
      ["po type", "Outbound Shipment Check", 1],
      ["item description", "Outbound Shipment Check", 1],
      ["sku", "Master License Validation", 1],
      ["location name", "Master License Validation", 1],
      ["license #", "Master License Validation", 1],
      ["lot", "Master License Validation", 1],
      ["qty", "Master License Validation", 1],
      ["qty alloc", "Master License Validation", 1],
      ["location on hand before", "Master License Validation", 1],
      ["function and emp id", "Master License Validation", 1],
      ["time completed", "Master License Validation", 1],
      ["license", "License Issue", 1],
      ["master license", "License Issue", 1],
      ["lot #", "License Issue", 1],
      ["sku", "License Issue", 1],
      ["lic qty", "License Issue", 1],
      ["license location", "License Issue", 1],
      ["inbound po#", "License Issue", 1],
      ["last receive datetime", "License Issue", 1],
      ["last putw date location", "License Issue", 1],
      ["last repl date location", "License Issue", 1],
      ["itemloc location", "License Issue", 1],
      ["itemloc sku", "License Issue", 1],
      ["itemloc on hand", "License Issue", 1],
      ["stage location", "License Issue", 1],
      ["wrk func code", "License Issue", 1],
      ["datetime added", "License Issue", 1],
      ["replen queue chk", "License Issue", 1],
      ["putaway queue chk", "License Issue", 1],
      ["cleanup staged work assignment", "Staged License Cleanup", 1],
      ["cleanup putaway license", "Staged License Cleanup", 1],
      ["date", "Staged License Cleanup", 1],
      ["stage location", "Staged License Cleanup", 1],
      ["work type", "Staged License Cleanup", 1],
      ["rpt id", "Report Email Address", 1],
      ["report name", "Report Email Address", 1],
      ["vendor #", "Report Email Address", 1],
      ["vendor name", "Report Email Address", 1],
      ["cn flg", "Report Email Address", 1],
      ["e mail address", "Report Email Address", 1],
      ["inbound po", "Recycled PO Check", 1],
      ["inbound load #", "Recycled PO Check", 1],
      ["inbound order type", "Recycled PO Check", 1],
      ["status", "Recycled PO Check", 1],
      ["vendor #", "Recycled PO Check", 1],
      ["vendor name", "Recycled PO Check", 1],
      ["sku", "Recycled PO Check", 1],
      ["sku description", "Recycled PO Check", 1],
      ["dept", "Recycled PO Check", 1],
      ["model / lot", "Recycled PO Check", 1],
      ["model/lot vendor name", "Recycled PO Check", 1],
      ["qty ord", "Recycled PO Check", 1],
      ["qty received", "Recycled PO Check", 1],
      ["orig po create date", "Recycled PO Check", 1],
      ["adj date & time", "Adjust Summary Detail", 1],
      ["day", "Adjust Summary Detail", 1],
      ["sku", "Adjust Summary Detail", 1],
      ["sku description", "Adjust Summary Detail", 1],
      ["dept", "Adjust Summary Detail", 1],
      ["adj loc", "Adjust Summary Detail", 1],
      ["model/ lot", "Adjust Summary Detail", 1],
      ["license", "Adjust Summary Detail", 1],
      ["new qty", "Adjust Summary Detail", 1],
      ["orig qty", "Adjust Summary Detail", 1],
      ["qty adj", "Adjust Summary Detail", 1],
      ["adjust cost", "Adjust Summary Detail", 1],
      ["abs adjust cost", "Adjust Summary Detail", 1],
      ["cartons adj", "Adjust Summary Detail", 1],
      ["abs cartons", "Adjust Summary Detail", 1],
      ["adj code", "Adjust Summary Detail", 1],
      ["adjustment description", "Adjust Summary Detail", 1],
      ["emp id", "Adjust Summary Detail", 1],
      ["wrk fnc", "Adjust Summary Detail", 1],
      ["week ind", "Cycle Count Progress", 1],
      ["week start", "Cycle Count Progress", 1],
      ["week end", "Cycle Count Progress", 1],
      ["expected qty", "Cycle Count Progress", 1],
      ["actual qty", "Cycle Count Progress", 1],
      ["inv accuracy %", "Cycle Count Progress", 1],
      ["locations counted", "Cycle Count Progress", 1],
      ["locations in error", "Cycle Count Progress", 1],
      ["location accuracy %", "Cycle Count Progress", 1],
      ["expected $$", "Cycle Count Progress", 1],
      ["actual $$", "Cycle Count Progress", 1],
      ["$$ inv accuracy %", "Cycle Count Progress", 1],
      ["empty locations counted", "Cycle Count Progress", 1],
      ["work fnc code", "Cycle Count Progress", 1],
      ["# auto wka", "Cycle Count Progress", 1],
      ["ttl # wka", "Cycle Count Progress", 1],
      ["# locations", "Cycle Count Progress", 1],
      ["zone", "Cycle Count Progress", 1],
      ["count datetime", "Cycle Count Progress", 1],
      ["sku", "Cycle Count Progress", 1],
      ["sku description", "Cycle Count Progress", 1],
      ["location name", "Cycle Count Progress", 1],
      ["model/ lot", "Cycle Count Progress", 1],
      ["orig emp id", "Cycle Count Progress", 1],
      ["emp id", "Cycle Count Progress", 1],
      ["wrk func", "Cycle Count Progress", 1],
      ["orig qty", "Cycle Count Progress", 1],
      ["count qty", "Cycle Count Progress", 1],
      ["variance", "Cycle Count Progress", 1],
      ["vari $$", "Cycle Count Progress", 1],
      ["wka", "Cycle Count Progress", 1],
      ["adj code", "Cycle Count Progress", 1],
      ["adj description", "Cycle Count Progress", 1],
      ["sku description", "SKU History Research", 1],
      ["unit cost", "SKU History Research", 1],
      ["lot cntrl", "SKU History Research", 1],
      ["lic cntrl", "SKU History Research", 1],
      ["locations in building", "SKU History Research", 1],
      ["quantity on hand", "SKU History Research", 1],
      ["quantity allocated", "SKU History Research", 1],
      ["open order qty", "SKU History Research", 1],
      ["# of open orders", "SKU History Research", 1],
      ["45 day pick hist", "SKU History Research", 1],
      ["45 day receive hist", "SKU History Research", 1],
      ["putaway history", "SKU History Research", 1],
      ["ib qty on order", "SKU History Research", 1],
      ["cca manual", "SKU History Research", 1],
      ["cca rf", "SKU History Research", 1],
      ["total cca", "SKU History Research", 1],
      ["cca loss/gain", "SKU History Research", 1],
      ["wka #", "Cycle Count Printout", 1],
      ["item #", "Cycle Count Printout", 1],
      ["location name", "Cycle Count Printout", 1],
      ["wfc", "Cycle Count Printout", 1],
      ["type", "Cycle Count Printout", 1],
      ["zone", "Cycle Count Printout", 1],
      ["date", "Cycle Count Printout", 1],
      ["wka barcode", "Cycle Count Printout", 1],
      ["license", "Putaway By Inbound Load", 1],
      ["sku", "Putaway By Inbound Load", 1],
      ["qty", "Putaway By Inbound Load", 1],
      ["to loc", "Putaway By Inbound Load", 1],
      ["location strg fnc", "Putaway By Inbound Load", 1],
      ["putaway id", "Putaway By Inbound Load", 1],
      ["datetime putw", "Putaway By Inbound Load", 1],
      ["receive id", "Putaway By Inbound Load", 1],
      ["datetime receive", "Putaway By Inbound Load", 1],
      ["sku description", "Putaway By Inbound Load", 1],
      ["work type", "Location History", 1],
      ["datetime", "Location History", 1],
      ["location name", "Location History", 1],
      ["sku", "Location History", 1],
      ["emp id", "Location History", 1],
      ["name", "Location History", 1],
      ["qty sched", "Location History", 1],
      ["qty actual", "Location History", 1],
      ["on hand before", "Location History", 1],
      ["on hand after", "Location History", 1],
      ["license or wka #", "Location History", 1],
      ["sku", "SKU Pick History", 1],
      ["sku description", "SKU Pick History", 1],
      ["mstr strategy description", "SKU Pick History", 1],
      ["total qty", "SKU Pick History", 1],
      ["ttl cartons", "SKU Pick History", 1],
      ["cp cartons", "SKU Pick History", 1],
      ["# cp wka", "SKU Pick History", 1],
      ["cp pallets", "SKU Pick History", 1],
      ["cp cube", "SKU Pick History", 1],
      ["fp cartons", "SKU Pick History", 1],
      ["# fp wka", "SKU Pick History", 1],
      ["fp pallets", "SKU Pick History", 1],
      ["fp cube", "SKU Pick History", 1],
      ["% cp", "SKU Pick History", 1],
      ["build on", "SKU Pick History", 1],
      ["sku", "SKUs on Order/Location", 1],
      ["sku description", "SKUs on Order/Location", 1],
      ["po type", "SKUs on Order/Location", 1],
      ["master strategy", "SKUs on Order/Location", 1],
      ["mstr strategy description", "SKUs on Order/Location", 1],
      ["ded loc", "SKUs on Order/Location", 1],
      ["dept", "SKUs on Order/Location", 1],
      ["cs qty", "SKUs on Order/Location", 1],
      ["pallet qty", "SKUs on Order/Location", 1],
      ["max cap", "SKUs on Order/Location", 1],
      ["max cap pallets", "SKUs on Order/Location", 1],
      ["total on hand", "SKUs on Order/Location", 1],
      ["pallets on hand", "SKUs on Order/Location", 1],
      ["cartons on order", "SKUs on Order/Location", 1],
      ["fp cartons", "SKUs on Order/Location", 1],
      ["cp cartons", "SKUs on Order/Location", 1],
      ["fp pallets", "SKUs on Order/Location", 1],
      ["cp pallets", "SKUs on Order/Location", 1],
      ["ded location turns", "SKUs on Order/Location", 1],
      ["sdc", "Item Configuration Report", 1],
      ["sku", "Item Configuration Report", 1],
      ["description", "Item Configuration Report", 1],
      ["dept", "Item Configuration Report", 1],
      ["itm config seq", "Item Configuration Report", 1],
      ["case qty", "Item Configuration Report", 1],
      ["case length", "Item Configuration Report", 1],
      ["case width", "Item Configuration Report", 1],
      ["case height", "Item Configuration Report", 1],
      ["case wgt", "Item Configuration Report", 1],
      ["case cube", "Item Configuration Report", 1],
      ["pallet qty", "Item Configuration Report", 1],
      ["pallet length", "Item Configuration Report", 1],
      ["pallet width", "Item Configuration Report", 1],
      ["pallet height", "Item Configuration Report", 1],
      ["pallet weight", "Item Configuration Report", 1],
      ["pallet cube", "Item Configuration Report", 1],
      ["qty on hand", "Item Configuration Report", 1],
      ["def rec crtn qty", "Item Configuration Report", 1],
      ["def pik crtn qty", "Item Configuration Report", 1],
      ["ti", "Item Configuration Report", 1],
      ["hi", "Item Configuration Report", 1],
      ["layer qty", "Item Configuration Report", 1],
      ["master strategy", "Item Configuration Report", 1],
      ["build on", "Item Configuration Report", 1],
      ["stack lmt", "Item Configuration Report", 1],
      ["unit value", "Item Configuration Report", 1],
      ["last cycle cnt", "Item Configuration Report", 1],
      ["last stg loc", "Item Configuration Report", 1],
      ["last dt rcvd", "Item Configuration Report", 1],
      ["sku", "SKUs on hold report", 1],
      ["sku description", "SKUs on hold report", 1],
      ["location name", "SKUs on hold report", 1],
      ["model lot", "SKUs on hold report", 1],
      ["case qty", "SKUs on hold report", 1],
      ["hold on rcpt", "SKUs on hold report", 1],
      ["hold code", "SKUs on hold report", 1],
      ["location on hand", "SKUs on hold report", 1],
      ["location qty on hold", "SKUs on hold report", 1],
      ["emp id", "SKUs on hold report", 1],
      ["datetime added", "SKUs on hold report", 1],
      ["mx location chk (# skus)", "SKUs on hold report", 1],
      ["zone", "Move Report", 1],
      ["vehicle type func", "Move Report", 1],
      ["repl wka", "Move Report", 1],
      ["wka bar code", "Move Report", 1],
      ["ovr hld", "Move Report", 1],
      ["status", "Move Report", 1],
      ["sku", "Move Report", 1],
      ["from loc", "Move Report", 1],
      ["qty", "Move Report", 1],
      ["pallets", "Move Report", 1],
      ["to loc", "Move Report", 1],
      ["location on hand", "Move Report", 1],
      ["location maxcap", "Move Report", 1],
      ["stage location", "Move Report", 1],
      ["stage license", "Move Report", 1],
      ["trailer #", "Move Report", 1],
      ["yard loc", "Move Report", 1],
      ["master strategy description", "Move Report", 1],
      ["datetime added", "Problem Resolution", 1],
      ["license", "Problem Resolution", 1],
      ["wrk fnc", "Problem Resolution", 1],
      ["pri", "Problem Resolution", 1],
      ["prob type", "Problem Resolution", 1],
      ["user prob type", "Problem Resolution", 1],
      ["problem description", "Problem Resolution", 1],
      ["orig emp", "Problem Resolution", 1],
      ["tran #", "Problem Resolution", 1],
      ["status", "Problem Resolution", 1],
      ["status description", "Problem Resolution", 1],
      ["yard loc", "Problem Resolution", 1],
      ["trailer #", "Problem Resolution", 1],
      ["ib load #", "Problem Resolution", 1],
      ["model lot", "Problem Resolution", 1],
      ["sku", "Problem Resolution", 1],
      ["master strategy", "Problem Resolution", 1],
      ["sku description", "Problem Resolution", 1],
      ["qty", "Problem Resolution", 1],
      ["rcv case qty", "Problem Resolution", 1],
      ["rcv pallet qty", "Problem Resolution", 1],
      ["location name", "Problem Resolution", 1],
      ["pr location", "Problem Resolution", 1],
      ["wka", "Problem Resolution", 1],
      ["fifo datetime", "Problem Resolution", 1],
      ["hold code flg", "Problem Resolution", 1],
      ["rtn flg", "Problem Resolution", 1],
      ["dmg flg", "Problem Resolution", 1],
      ["rcv pt", "Problem Resolution", 1],
      ["hot itm flg", "Problem Resolution", 1],
      ["src doc num", "Problem Resolution", 1],
      ["yard loc", "Yard Report", 1],
      ["location type", "Yard Report", 1],
      ["location hold", "Yard Report", 1],
      ["trailer #", "Yard Report", 1],
      ["scac", "Yard Report", 1],
      ["trailer status", "Yard Report", 1],
      ["arrival", "Yard Report", 1],
      ["inb / outb", "Yard Report", 1],
      ["empty/ full", "Yard Report", 1],
      ["ob freight bill", "Yard Report", 1],
      ["hold code", "Yard Report", 1],
      ["storage trailer contents", "Yard Report", 1],
      ["catalyst location", "Yard Report", 1],
      ["yms load #", "Yard Report", 1],
      ["val code", "Yard Report", 1],
    ]
      //   .map(([a, b, c]) => [b, a, c])
      .sort((l1, l2) => l1[0].localeCompare(l2[0]))
      .filter(
        (element, index, ary) =>
          ary.filter((el) => keepSingles || el[0] === element[0]).length > 1
      )
  );

  // Sets chart options.
  var options = {
    width: 600,
  };

  // Instantiates and draws our chart, passing in some options.
  var chart = new google.visualization.Sankey(
    document.getElementById("sankey_basic")
  );
  chart.draw(data, options);
}
